### ISSUE TITLE
Did I break the docs site?

### ISSUE THREAD

**Issue by darthsteven** [phpseclib/phpseclib.github.io#2]
After you merged #1 I think the docs site went 💥 

![v3docs___phpseclib_github_io](https://github.com/phpseclib/phpseclib.github.io/assets/95782/f0167e09-21b9-4c46-b946-a851e9158d71)

**Comment by terrafrost** [comment]
Your PR didn't break it - github broke it. Like if I changed any file, myself, the documentation website would have still broken.

Turns out the issue was this:

https://github.com/phpseclib/phpseclib.github.io/commit/3223836bf48b3805030d4b6afe7363cccde2bf96

In .github/workflows/ci.yml I'm checking out the `actions/setup-node@v3` module with a few parameters set. I guess github updated the `actions/setup-node@v3` module at some point in a way that broke my script.
